#! /bin/sh

if [ -e Reference ]
then
	rm -r Reference
fi

headerdoc2html -u -t -o Reference ../KeyNaming.h
#gatherheaderdoc Reference/ KeyNaming.html
cd Reference
ln -s KeyNaming/index.html KeyNaming.html
